#!/usr/bin/env bash

###############################################################################@
#
# @BEGIN
# @COPYRIGHT BEGIN
# Copyright (C) 2019 Panos I. Papadopoulos <panos1962_AT_gmail_DOT_com>
# @COPYRIGHT END
#
# @FILE BEGIN
# lib/govHUB/carget —— Πρόγραμμα αναζήτησης οχημάτων μέσω πλατφόρμας "govHUB"
# @FILE END
#
# @DESCRIPTION BEGIN
# Το παρόν πρόγραμμα είθισται να καλείται εμμέσως, μέσω του προγράμματος
# "govHUB" ως εξής:
#
#	govHUB carget [OPTIONS] [ARGUMENTS]
#
# ή 
#
#	GH carget [OPTIONS] [ARGUMENTS]
#
# Το πρόγραμμα σκοπό έχει να ζητήσει από την πλατφόρμα "govHUB" δεδομένα που
# αφορούν σε οχήματα καταγεγραμμένα στις βάσεις δεδομένων του Υπουργείου
# Οικονομικών. Τα στοιχεία που απαιτούνται προκειμένου να αναζητηθούν και να
# επιστραφούν δεδομένα για κάποιο όχημα είναι ο αριθμός κυκλοφορίας τού
# οχήματος και μια ημερομηνία για την οποία αιτούμαστε δεδομένα οχήματος και
# κατόχων.
#
# Το πρόγραμμα χρησιμοποιείται κυρίως για την εξακρίβωση των στοιχείων κατόχων
# των οχημάτων, προκειμένου να βεβαιωθούν στα αντίστοιχα ΑΦΜ πρόστιμα από
# παραβάσεις ΚΟΚ στις οποίες έχουν υποπέσει τα συγκεκριμένα οχήματα. Επειδή
# οι παραβάσεις χαρακτηρίζονται μονοσήμαντα από κάποιου είδους κωδικό (id,
# primary key κλπ), το πρόγραμμα μπορεί να δέχεται τον κωδικό της παράβασης
# προκειμένου στο output να εκτυπώνεται και ο εν λόγω κωδικός παράβασης, μαζί
# με τα στοιχεία κατόχου.
# @DESCRIPTION END
#
# @HISTORY BEGIN
# Updated: 2019-12-16
# @HISTORY END
# @END
#
###############################################################################@

pd_tmpmax="1"
. "${PANDORA_BASEDIR:=/var/opt/pandora}/lib/pandora.sh"

pd_seterrcode \
	"fserr" \
	""

tmp1="${pd_tmpname[1]}"
pd_sigtrap

eval set -- "$(pd_parseopts "s:v" "script:,verbose" "$@")"
[ $1 -ne 0 ] && pd_usage
shift

cat "${CHT_BASEDIR:=/var/opt/cht}/lib/govHUB/carget.js" >"${tmp1}"

error=
verbose=

for arg in "$@"
do
	case "${arg}" in
	-v|--verbose)
		verbose="yes"
		shift 1
		;;
	-s|--script)
		cat "${2}" >>"${tmp1}" || error="yes"
		shift 2
		;;
	--)
		shift 1
		;;
	esac
done
unset arg

[ -z "${verbose}" ] &&
echo "pd.ttyMute();" >>"${tmp1}"

[ -n "${error}" ] &&
pd_exit "fserr"

echo "carget.init();" >>"${tmp1}"
cat "$@" | node "${tmp1}"

pd_exit
