#!/usr/bin/env bash

# Το παρόν πρόγραμμα είθισται να καλείται εμμέσως, μέσω του προγράμματος
# "govHUB" ως εξής:
#
#	govHUB carget [OPTIONS] [ARGUMENTS]
#
# Αν έχετε δημιουργήσει link "GH" για το πρόγραμμα "govHUB" μπορείτε να
# καλέσετε το παρόν και με την εντολή:
#
#	GH carget [OPTIONS] [ARGUMENTS]
#
# Το πρόγραμμα σκοπό έχει να ζητήσει από την πλατφόρμα "govHUB" δεδομένα που
# αφορούν σε οχήματα καταγεγραμμένα στις βάσεις δεδομένων του Υπουργείου
# Οικονομικών. Τα στοιχεία που απαιτούνται προκειμένου να αναζητηθούν και
# επιστραφούν δεδομένα για κάποιο όχημα είναι ο αριθμός κυκλοφορίας τού
# οχήματος και μια ημερομηνία για την οποία αιτούμαστε δεδομένα οχήματος.
# Αν δεν καθορίσουμε ημερομηνία, τότε επιστρέφονται δεδομένα για την τρέχουσα
# ημερομηνία.
#
# Το πρόγραμμα χρησιμοποιείται κυρίως για την εξακρίβωση των στοιχείων κατόχων
# των οχημάτων, προκειμένου να βεβαιωθούν στα αντίστοιχα ΑΦΜ πρόστιμα από
# παραβάσεις ΚΟΚ στις οποίες έχουν υποπέσει τα συγκεκριμένα οχήματα. Επειδή
# οι παραβάσεις χαρακτηρίζονται μονοσήμαντα από κάποιου είδους κωδικό (id,
# primary key κλπ), το πρόγραμμα μπορεί να δέχεται τον κωδικό της παράβασης
# προκειμένου στο output να εκτυπώνεται και ο εν λόγω κωδικός παράβασης, μαζί
# με τα στοιχεία κατόχου.

pd_tmpmax="1"
. "${PANDORA_BASEDIR:=/var/opt/pandora}/lib/pandora.sh"

pd_seterrcode \
	"govhuberr" \
	"tokenerr" \
	"paramerr" \
	"autoerr" \
	"othererr" \
	""

tmp1="${pd_tmpname[1]}"
pd_sigtrap

govhubcf="${CHT_BASEDIR:=/var/opt/cht}/private/govHUB.cf"
client_id=
client_secret=
token=
token_file=
user_id=
user_ip=
protocol_number=
protocol_date=
sep=
ofs=
kodikos_col=
pinakida_col=
imerominia_col=

eval set -- "$(getopt -n "${pd_progname}" \
--options "G:c:s:t:f:u:i:p:d:" \
--long "govHUB-conf:,client_id:,client_secret:,token:,token_file:,\
user_id:,user_ip:,protocol_number:,protocol_date:,\
fs:,sep:,separator:,ofs:,
id-column:,license-column:,date-column:" -- "$@")" ||
pd_usage

for arg in "$@"
do
	case "${arg}" in

	-F|--govHUB-conf)
		govhubcf="${2}"
		shift 2
		;;

	-c|--client_id)
		client_id="${2}"
		shift 2
		;;

	-s|--client_secret)
		client_secret="${2}"
		shift 2
		;;

	-t|--token)
		connect_token="${2}"
		shift 2
		;;

	-f|--token_file)
		token_file="${2}"
		shift 2
		;;

	-u|--user_id)
		user_id="${2}"
		shift 2
		;;

	-i|--user_ip)
		user_ip="${2}"
		shift 2
		;;

	-p|--protocol_number)
		protocol_number="${2}"
		shift 2
		;;

	-d|--protocol_date)
		protocol_date="${2}"
		shift 2
		;;

	--fs|--sep|--separator)
		sep="${2}"
		shift 2
		;;

	--ofs)
		ofs="${2}"
		shift 2
		;;

	--id-column)
		kodikos_col="${2}"
		shift 2
		;;

	--license-column)
		pinakida_col="${2}"
		shift 2
		;;

	--date-column)
		imerominia_col="${2}"
		shift 2
		;;

	--)
		shift 1
		;;
	esac
done
unset arg

. "${govhubcf}" ||
pd_exit "govhuberr"

token_set() {
	[ -n "${token}" ] &&
	return 0

	if [ -n "${token_file}" ]; then
		token="$(cat "${token_file}" 2>/dev/null)" &&
		return 0

		pd_errmsg "${token_file}: cannot read file" &&
		pd_exit "tokenerr"
	fi

	[ -z "${GH_oxima_tokenget_client_id}" ] &&
	pd_errmsg "get-token: unspecified client_id" &&
	error="yes"

	[ -z "${GH_oxima_tokenget_client_secret}" ] &&
	pd_errmsg "get-token: unspecified client_secret" &&
	error="yes"

	[ -n "${error}" ] &&
	return 1

	[ -z "${GH_oxima_tokenget_url}" ] &&
	GH_oxima_tokenget_url="https://auth.govhub.gr/connect/token"

	curl \
	--silent \
	--request "POST" \
	--url "https://auth.govhub.gr/connect/token" \
	--header "content-type: application/x-www-form-urlencoded" \
	--data "grant_type=client_credentials" \
	--data "client_id=${GH_oxima_tokenget_client_id}" \
	--data "client_secret=${GH_oxima_tokenget_client_secret}" \
	--data "response_type=code token" \
	--data "scope=GovHub.GsisVehicle.Basic" >"${tmp1}"

	[ $? -ne 0 ] &&
	pd_errmsg "failed to get token" &&
	pd_exit "tokenerr"

	token="$(jq --monochrome-output --raw-output '.access_token' "${tmp1}")" &&
	return 0

	pd_errmsg "failed to parse token json"
	return 1
}

user_set() {
	local fake_ip="10.65.15.45"

	[ -z "${user_id}" ] &&
	user_id="dorak"

	[ -z "${user_ip}" ] &&
	user_ip="$(hostname -I)"

	[ -z "${user_ip}" ] &&
	pd_errmsg "warning: failed to get local IP address set to ${fake_ip}" &&
	user_ip="${fake_ip}"

	return 0
}

error=

token_set || error="yes"
user_set || error="yes"

[ -n "${error}" ] &&
pd_exit "othererr"

# Το προσωρινό αρχείο "tmp1" θα χρησιμοποιηθεί κατά τη διαδικασία της
# αναζήτησης στοιχείων οχημάτων/κατόχων, καθώς δεν έχουμε κανέναν έλεγχο
# στο πρόγραμμα αναζήτησης και στο τι αυτό επιστρέφει σε περίπτωση που τα
# παράγματα δεν πάνε καλά. Ενώ υπάρχουν πεδία στο επιστρεφόμενο JSON object
# τα οποία αφορούν σε σφάλματα που ενδεχομένως προέκυψαν κατά τη διαδικασία
# της αναζήτησης, κάποιες φορές απλώς το πρόγραμμα δεν επιστρέφει απολύτως
# τίποτα, όπως συμβαίνει π.χ. αν χρησιμοποιήσουμε «ληγμένο» connect token.

rm -f "${tmp1}"

awk \
-v sep="${fs}" \
-v ofs="${ofs}" \
-v kodikos_col="${kodikos_col}" \
-v pinakida_col="${pinakida_col}" \
-v imerominia_col="${imerominia_col}" \
-v simera="$(date +"%Y-%m-%d")" \
-v protocol_date="${protocol_date}" \
-v protocol_number="${protocol_number}" \
-v url="${GH_oxima_dataget_url}" \
-v token="${token}" \
-v user_id="${GH_oxima_dataget_user_id[0]}" \
-v user_ip="${GH_oxima_dataget_user_ip[0]}" \
-i "${PANDORA_BASEDIR}/lib/pandora.awk" \
-f "${CHT_BASEDIR}/lib/govHUB/carget.awk" "$@" &&
pd_exit 0

pd_exit "autoerr"
