#!/usr/bin/env bash
. "${PANDORA_BASEDIR:=/var/opt/pandora}/lib/pandora.sh"

eval set -- "$(getopt -n "${pd_progname}" \
--options "" \
--long "" \
-- "$@")" ||
pd_usage

for arg in "$@"
do
	case "${arg}" in
	--)
		shift 1
		;;
	esac
done
unset arg

parser="jq"
parser="${parser} --raw-output"
parser="${parser} --monochrome-output"
parser="${parser} --stream"

${parser} '
("ΚΩΔΙΚΟΣ " + (select(.[0][0] == "id")|.[1])),
("ΗΜΕΡΟΜΗΝΙΑ " + (select(.[0][0] == "date")|.[1])),
("ΠΙΝΑΚΙΔΑ " + (select((.[0][0] == "vehicle") and
	(.[0][1] == "getVehicleInformationOutputRecord") and
	(.[0][2] == "arithmosKykloforias"))|.[1])),
(select((.[0][0] == "vehicle") and
	(.[0][1] == "getVehicleInformationOutputRecord") and
	(.[0][2] == "katoxoiList"))|
	("ΑΦΜ " + (select(.[0][4] == "afm")|.[1])),
	("ΠΟΣΟΣΤΟ " + (select(.[0][4] == "percent")|.[1])),
	("ΔΟΥ " + (select(.[0][4] == "doy")|.[1])),
	("ΠΕΡΙΓΡΑΦΗ ΔΟΥ " + (select(.[0][4] == "doyDesc")|.[1])),
	("ΕΠΩΝΥΜΟ1 " + (select(.[0][4] == "surname")|.[1])),
	("ΕΠΩΝΥΜΟ2 " + (select(.[0][4] == "secondSurname")|.[1])),
	("ΟΝΟΜΑ " + (select(.[0][4] == "firstName")|.[1])),
	("ΠΑΤΡΩΝΥΜΟ " + (select(.[0][4] == "fathersName")|.[1])),
	("ΜΗΤΡΩΝΥΜΟ " + (select(.[0][4] == "mothersName")|.[1])),
	("ΟΔΟΣ " + (select(.[0][4] == "address")|.[1])),
	("ΑΡΙΘΜΟΣ " + (select(.[0][4] == "addressNo")|.[1])),
	("ΤΚ " + (select(.[0][4] == "parZipCode")|.[1])),
	("ΠΕΡΙΟΧΗ " + (select(.[0][4] == "parDescription")|.[1]))
)
' "$@"
