#!/usr/bin/env bash

###############################################################################@
#
# Copyright (C) 2019 Panos I. Papadopoulos <panos1962_AT_gmail_DOT_com>
#
# Updated: 2019-12-20
#
###############################################################################@

exec node -e "const w3srv = require('${CHT_BASEDIR:=/var/opt/cht}/lib/govHUB/w3srv.js');
w3srv.init();"
