SELECT
KLHTKLHSEIS.ID,
SUBSTR(KLHTVEHICLESHD.LICENCENUM, 1, 10),
KLHTKLHSEIS.KLHDTE

FROM
KLHTKLHSEIS
LEFT OUTER JOIN KLHTVEHICLESHD
ON KLHTKLHSEIS.KVH_ID = KLHTVEHICLESHD.ID

WHERE KLHTKLHSEIS.COM_ID = 61
AND KLHTKLHSEIS.CUH_ID IS NULL
AND KLHTKLHSEIS.AKIROFLAG = 0
--AND ROWNUM < 10000

ORDER BY
KLHTKLHSEIS.KLHDTE DESC,
KLHTKLHSEIS.ID DESC
;
