#!/usr/bin/env bash

[ -z "CHT_BASEDIR" ] &&
CHT_BASEDIR="/var/opt/cht"

libdir="${CHT_BASEDIR}/lib/ekdda/paratiritirio"

pd_sqlplus -F "${CHT_BASEDIR}/private/opsoidb.cf" \
"${libdir}/prosopiko.sql" |\
sort -t "	" |\
awk -f "${libdir}/prosopiko.awk" "${libdir}/spoudes.tsv" -
