#!/usr/bin/env bash

pd_tmpmax=2
. "${PANDORA_BASEDIR:=/var/opt/pandora}/lib/pandora.sh"

pd_tmpname[1]="${pd_tmpname[1]}.xls"
pd_tmpname[2]="${pd_tmpname[2]}.txt"

ofile="${pd_tmpname[1]}"
efile="${pd_tmpname[2]}"

pd_sigtrap

pd_usagemsg="[ --full ] [ --excel=file ] [--mail=emails ] [ --cc=emails ]"

eval set -- $(pd_parseopts "fx:m:c:" "full,excel:,mail:,cc:" $*)

[ "$1" != "0" ] &&
pd_usage

shift

mail_push() {
	local i
	local err=0

	for i in $(echo "$@" | sed 's;,; ;g')
	do
		pd_isemail "${i}" &&
		mail="${mail} ${i}" &&
		continue

		pd_errmsg "${i}: invalid email address" &&
		err=1
	done

	return ${err}
}

cc_push() {
	local i
	local err=0

	for i in $(echo "$@" | sed 's;,; ;g')
	do
		pd_isemail "${i}" &&
		cc="${cc} -c ${i}" &&
		continue

		pd_errmsg "${i}: invalid cc email address" &&
		err=1
	done

	return ${err}
}

fulldata=
excel=
mail=
cc=
error=

for opt in "$@"
do
	case "${opt}" in
	-f|--full)
		fulldata="yes"
		shift
		;;
	-x|--excel)
		excel="${2}.xls"
		shift 2
		;;
	-m|--mail)
		mail_push "$2"
		shift 2
		;;
	-c|--cc)
		cc_push "$2"
		shift 2
		;;
	--)
		shift
		break
		;;
	esac
done

[ $# -ne 0 ] &&
pd_usage

[ -n "${mail}" ] &&
[ -z "${excel}" ] &&
excel="${ofile}"

[ -n "${error}" ] &&
exit 2

[ -z "CHT_BASEDIR" ] &&
CHT_BASEDIR="/var/opt/cht"

libdir="${CHT_BASEDIR}/lib/paratiritirio"

[ -n "${excel}" ] &&
post="|ssconvert \
--import-type=Gnumeric_stf:stf_csvtab \
--export-type=Gnumeric_Excel:xlsx2 \
fd://0 fd://1 >${excel}"

pd_sqlplus -F "${CHT_BASEDIR}/private/opsoidb.cf" "${libdir}/prosopiko.sql" |\
sort -t "	" |\
awk \
-v "mode=${mode}" \
-v "fulldata=${fulldata}" \
-f "${libdir}/prosopiko.awk" \
"${libdir}/prosopiko_spoudes.tsv" - 2>"${efile}" |\
eval sort -t "'$(echo -e "\t")'" -k2n ${post}

[ -z "${mail}" ] &&
cat "${efile}" >&2 &&
pd_tmpcleanup &&
exit 0

mail \
-r 'ΤΠΕ <tpe@thessaloniki.gr>' \
-s 'Στοιχεία προσωπικού για το «Παρατηρητήριο» του Δήμου Θεσσαλονίκης' \
-a "${ofile}" \
-a "${efile}" \
${cc} ${mail} <<+++
Αποστολή στοιχείων Προσωπικού για το «Παρατηρητήριο» του Δήμου Θεσσαλονίκης.
Συνημμένα θα βρείτε \
α) αρχείο Excel με τα ζητούμενα στοιχεία προσωπικού, και \
β) αρχείο λαθών που εντοπίστηκαν κατά την αναζήτηση των στοιχείων.
+++

pd_tmpcleanup
exit 0
